### ISSUE TITLE
ros melodic

### ISSUE THREAD

**Issue by Yousef-Alhattab** [SyllogismRXS/moos-ros-bridge#3]
can it be used in ros melodic, please?

and please any more tutorial on it! could you share?

**Comment by SyllogismRXS** [comment]
I haven't used it in a while, but it will probably work in melodic if you build it in a catkin workspace on your local system.

**Comment by Yousef-Alhattab** [comment]
thanks a lot 
I am working on it trying to run it 
will let you know
thanks again

**Comment by urbansound8K** [comment]
could you bear with me please 

ever time I tried to start the MOOS Database, I get this error 


------------------- MOOSDB V10 -------------------
  Hosting  community                "#1"
  Name look up is                   off
  Asynchronous support is           on
  Connect to this server on port    9000
--------------------------------------------------
network performance data published on localhost:9020
listen with "nc -u -lk 9020"
1665473787.4761   disabling nagle
Error binding to listen socket - Is there another CommServer Running?
This Server Is Quitting


how to solve it please?

**Comment by urbansound8K** [comment]
please bear with me!
what I have done is the following 
I ran: 
1) MOOSDB
2) roscore
3) rosrun moos-ros-bridge counter.sh
then I connected and this what I got:
/home/cute/Pictures/Screenshot from 2022-10-11 18-03-20.png

the rest before this was as you mentioned I got the 42 output


my question is that now I am running my node. it is point cloud with object detection 
how can I connect it to Moos using ur code?
I am new for being Moos user, please
